# Generated by Django 5.1.12 on 2025-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='Whether user has completed the onboarding process', verbose_name='Is Onboarded'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of category codes the user is interested in', verbose_name='Preferred Categories'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_sources',
            field=models.JSONField(blank=True, default=list, help_text='List of source IDs the user prefers', verbose_name='Preferred Sources'),
        ),
    ]
