# Generated by Django 5.1.12 on 2025-09-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_userpreference_options_and_more'),
        ('users', '0002_userprofile_is_onboarded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_categories',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_sources',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories the user is interested in', related_name='users', to='news.category', verbose_name='Preferred Categories'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_sources',
            field=models.ManyToManyField(blank=True, help_text='News sources the user prefers', related_name='users', to='news.newssource', verbose_name='Preferred Sources'),
        ),
    ]
