# Generated by Django 5.1.12 on 2025-09-22 01:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('query', models.CharField(db_index=True, help_text='The search query entered by the user', max_length=500, verbose_name='Search Query')),
                ('normalized_query', models.CharField(blank=True, db_index=True, help_text='Normalized version of the query for analysis', max_length=500, verbose_name='Normalized Query')),
                ('search_type', models.CharField(choices=[('article', 'Article Search'), ('category', 'Category Search'), ('source', 'Source Search'), ('autocomplete', 'Autocomplete'), ('trending', 'Trending Search')], default='article', max_length=20, verbose_name='Search Type')),
                ('result_count', models.IntegerField(default=0, help_text='Number of results returned', verbose_name='Result Count')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Search response time in milliseconds', null=True, verbose_name='Response Time (ms)')),
                ('filters_applied', models.JSONField(blank=True, default=dict, help_text='JSON object containing applied search filters', verbose_name='Filters Applied')),
                ('clicked_result_position', models.IntegerField(blank=True, help_text='Position of the search result that was clicked (1-based)', null=True, verbose_name='Clicked Result Position')),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Session identifier for anonymous users', max_length=100, verbose_name='Session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Search Analytics',
                'verbose_name_plural': 'Search Analytics',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['sentiment_score'], name='news_articl_sentime_9bf234_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='news_articl_search__6fe81f_gin'),
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='clicked_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to='news.article', verbose_name='Clicked Article'),
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_analytics', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['user'], name='news_search_user_id_a8ba15_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['query'], name='news_search_query_02b1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['normalized_query'], name='news_search_normali_e04c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['search_type'], name='news_search_search__a4c4cd_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['result_count'], name='news_search_result__185e66_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['created'], name='news_search_created_2a5555_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['session_id'], name='news_search_session_04d416_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['clicked_article'], name='news_search_clicked_2c9a5b_idx'),
        ),
    ]
