# Generated by Django 5.1.12 on 2025-09-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_searchanalytics_article_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.RemoveIndex(
            model_name='searchanalytics',
            name='news_search_session_04d416_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchanalytics',
            name='news_search_clicked_2c9a5b_idx',
        ),
        migrations.RemoveField(
            model_name='searchanalytics',
            name='clicked_article',
        ),
        migrations.RemoveField(
            model_name='searchanalytics',
            name='clicked_result_position',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='scroll_depth',
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data about the interaction', verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='primary_category',
            field=models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('politics', 'Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('science', 'Science'), ('world', 'World')], default='technology', max_length=20, verbose_name='Primary Category'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='filters_applied',
            field=models.JSONField(blank=True, default=dict, help_text='Filters used in the search', verbose_name='Filters Applied'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='normalized_query',
            field=models.CharField(help_text='Lowercased and cleaned query for analysis', max_length=500, verbose_name='Normalized Query'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='query',
            field=models.CharField(max_length=500, verbose_name='Search Query'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='response_time_ms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Response Time (ms)'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='result_count',
            field=models.IntegerField(default=0, verbose_name='Result Count'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='search_type',
            field=models.CharField(choices=[('article', 'Article Search'), ('autocomplete', 'Autocomplete'), ('trending', 'Trending Search')], default='article', max_length=20, verbose_name='Search Type'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('comment', 'Comment'), ('click', 'Click')], max_length=20, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='reading_time',
            field=models.IntegerField(blank=True, help_text='Time spent reading the article', null=True, verbose_name='Reading Time (seconds)'),
        ),
    ]
