# Generated by Django 5.1.12 on 2025-09-20 16:59

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notification_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome'), ('news_digest', 'News Digest'), ('account_update', 'Account Update')], max_length=50, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], default='email', max_length=20, verbose_name='Channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('content', models.TextField(verbose_name='Content')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Recipient Email')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Recipient Phone')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data related to the notification', verbose_name='Metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['status', 'created'], name='notificatio_status_f82d57_idx'), models.Index(fields=['channel', 'sent_at'], name='notificatio_channel_3c710d_idx')],
            },
        ),
    ]
